// Time section
export const TIME_SECONDS_1_IN_MILLISECONDS: number = 1000;
export const TIME_SECONDS_4_IN_MILLISECONDS: number = 4 * TIME_SECONDS_1_IN_MILLISECONDS;
export const TIME_SECONDS_10_IN_MILLISECONDS: number = 10 * TIME_SECONDS_1_IN_MILLISECONDS;
export const TIME_SECONDS_20_IN_MILLISECONDS: number = 20 * TIME_SECONDS_1_IN_MILLISECONDS;
export const TIME_SECONDS_40_IN_MILLISECONDS: number = 40 * TIME_SECONDS_1_IN_MILLISECONDS;
export const TIME_SECONDS_60_IN_MILLISECONDS: number = 60 * TIME_SECONDS_1_IN_MILLISECONDS;

export const TIME_MINUTES_1_IN_MILLISECONDS: number = 60 * TIME_SECONDS_1_IN_MILLISECONDS;
export const TIME_MINUTES_2_IN_MILLISECONDS: number = 2 * TIME_MINUTES_1_IN_MILLISECONDS;
export const TIME_MINUTES_3_IN_MILLISECONDS: number = 3 * TIME_MINUTES_1_IN_MILLISECONDS;
export const TIME_MINUTES_5_IN_MILLISECONDS: number = 5 * TIME_MINUTES_1_IN_MILLISECONDS;
export const TIME_MINUTES_6_IN_MILLISECONDS: number = 6 * TIME_MINUTES_1_IN_MILLISECONDS;
export const TIME_MINUTES_10_IN_MILLISECONDS: number = 10 * TIME_MINUTES_1_IN_MILLISECONDS;
export const TIME_MINUTES_20_IN_MILLISECONDS: number = 20 * TIME_MINUTES_1_IN_MILLISECONDS;
export const TIME_MINUTES_30_IN_MILLISECONDS: number = 30 * TIME_MINUTES_1_IN_MILLISECONDS;
